kind: Service
apiVersion: v1
metadata:
  name: demo-service
spec:
  selector:
    app: pipe-demo
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipe-demo
  labels:
    app: pipe-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipe-demo
  template:
    metadata:
      labels:
        app: pipe-demo
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: maven
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
